# Generated by Django 4.2.6 on 2023-10-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_photos/'),
        ),
    ]
