# Generated by Django 4.2.7 on 2023-11-24 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_currency_listed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='listed_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 18, 52, 14, 294316)),
        ),
    ]
