# Generated by Django 4.2.5 on 2023-11-26 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_currency_options_remove_currency_btc_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={},
        ),
        migrations.RemoveField(
            model_name='currency',
            name='code',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='rate_to_usd',
        ),
        migrations.AddField(
            model_name='currency',
            name='btc_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='currency',
            name='change',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='currency',
            name='color',
            field=models.CharField(default='red', max_length=10),
        ),
        migrations.AddField(
            model_name='currency',
            name='icon_url',
            field=models.URLField(default='https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg'),
        ),
        migrations.AddField(
            model_name='currency',
            name='listed_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 23, 34, 18, 864637)),
        ),
        migrations.AddField(
            model_name='currency',
            name='low_volume',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currency',
            name='market_cap',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='currency',
            name='name',
            field=models.CharField(default='Bitcoin', max_length=255),
        ),
        migrations.AddField(
            model_name='currency',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='currency',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currency',
            name='sparkline',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='tier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currency',
            name='uuid',
            field=models.CharField(default=0, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='volume_24hr',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='BTS', max_length=10),
        ),
    ]
