# Generated by Django 4.2.5 on 2023-11-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_currency_options_remove_currency_btc_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='price_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
