# Generated by Django 4.2.7 on 2023-11-24 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_currency_listed_at_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='NULL', max_length=4),
        ),
        migrations.AlterField(
            model_name='currency',
            name='listed_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 20, 14, 6, 648812)),
        ),
    ]
