# Generated by Django 4.2.7 on 2023-11-26 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_purchase_transaction_type_alter_currency_listed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptopricehistory',
            name='market_cap',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cryptopricehistory',
            name='supply',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cryptopricehistory',
            name='volume',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='listed_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 2, 54, 3, 274150)),
        ),
    ]
