# Generated by Django 4.2.7 on 2023-11-26 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_cryptopricehistory_market_cap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptopricehistory',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='cryptopricehistory',
            name='supply',
        ),
        migrations.RemoveField(
            model_name='cryptopricehistory',
            name='volume',
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='market_cap',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='supply',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='volume',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='listed_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 2, 56, 3, 895036)),
        ),
    ]
