# Generated by Django 4.2.5 on 2023-11-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='symbol',
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='logo',
            field=models.ImageField(default=1, upload_to='cryptocurrency_logos/'),
            preserve_default=False,
        ),
    ]
